name: publish

on:
  push:
    branches:
      - web

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v5
      - name: dockerhub
        uses: docker/login-action@v3
        with:
          username: juftin
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: buildx
        uses: docker/setup-buildx-action@v3
      - name: bake
        uses: docker/bake-action@v6
        with:
          push: true
          targets: backend
        env:
          BACKEND_VERSION: latest
